/**
 * Created by Adebola on 09/02/2016.
 */

var Tout,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

Tout = (function(superClass) {
    extend(Tout, superClass);

    Tout.SHOUT_EVENT = "shout_event";

    function Tout() {
        this.iShout = 0;
        Tout.__super__.constructor.call(this);
        return;
    }

    Tout.prototype.shoutOut = function() {
        this.iShout += 1;
        this.notify(Tout.SHOUT_EVENT, "shouting - " + this.iShout + " time(s)");
    };

    return Tout;

})(Observant);

// ---
// generated by coffee-script 1.9.2


$(document).ready(function(){
    window.oToutPerson = new Tout();
   $("#shoutOut").on('click', function(){
       oToutPerson.shoutOut();
   });


    oToutPerson.observe(Tout.SHOUT_EVENT, function(sMessage){
       $("ol#listMessage").append("<li>"+sMessage+"</li>");
    });

});

